export { default as Home } from './Home/Home'
export { default as Shop } from './Shop/Shop'
export { default as About } from './About/About'
export { default as Contact } from './Contact/Contact'
export { default as Login } from './Login/Login'
